### ISSUE TITLE
Inquiry about the generalization of this method

### ISSUE THREAD

**Issue by zhaisf** [Robin-WZQ/T2IShield#1]
Thank you for your insightful work!

I would like to ask that besides [**Rickrolling**](https://arxiv.org/abs/2211.02408) and [**Villain Diffusion**](https://arxiv.org/abs/2306.06874),  if your method is also effective against other mainstream text-to-image backdoor attacks ?

For examples, the [**BadT2I**](https://arxiv.org/abs/2305.04175) and the [**Personalization  Backdoor**](https://arxiv.org/abs/2305.10701). 
Have you conducted experiments against these  backdoor attacks?

**Comment by Robin-WZQ** [comment]
Hi @zhaisf ,

Apologies for the late response. We didn't test our method on “BadT2I” and “Personalization Backdoor” because their code was not fully available before the ECCV submission deadline.

We tested BadT2I this week but did not observe evidence of the 'Assimilation Phenomenon,' which might potentially cause our detection mechanism to be bypassed. We will release all the detection, localization, and mitigation code within two weeks and welcome any testing!

Thanks.

**Comment by oscarchew** [comment]
Interestingly, our team also find that Assimilation Phenomenon does not occur in Textual Inversion (which is one of the personalization backdoors). Check out our latest ECCV workshop paper (https://www.arxiv.org/abs/2408.15721) for more information. 🤗

**Comment by Robin-WZQ** [comment]
Hi @oscarchew 

Thank you very much for informing us about your great work. We will read your paper carefully!

BTW if you will be attending ECCV in Milan, I look forward to discussing backdoor defense with you there! 🤗
